BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS `telephone` (
	`id`	INTEGER NOT NULL UNIQUE,
	`contact_id`	INTEGER NOT NULL,
	`number`	TEXT NOT NULL,
	`description`	TEXT,
	PRIMARY KEY(`id`)
);
CREATE TABLE IF NOT EXISTS `contact` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`name`	TEXT NOT NULL,
	`last_name`	TEXT NOT NULL,
	`birth_date`	TEXT
);
CREATE TABLE IF NOT EXISTS `address` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`contact_id`	INTEGER NOT NULL,
	`street`	TEXT NOT NULL,
	`floor`	TEXT NOT NULL,
	`city`	TEXT NOT NULL,
	`zip_code`	TEXT
);
COMMIT;
